version: '2'
services:
    zookeeper1:
        image: zookeeper
        restart: always
        container_name: zookeeper1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: quorumListenOnAllIPs:true server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    zookeeper2:
        image: zookeeper
        restart: always
        container_name: zookeeper2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: quorumListenOnAllIPs:true server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    zookeeper3:
        image: zookeeper
        restart: always
        container_name: zookeeper3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: quorumListenOnAllIPs:true server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    nginx:
        image: nginx
        restart: always
        container_name: nginx
        ports:
        - 8080:80
        - 443:443